//! MSB-first bit writer, a bit counter with the same interface (so the frame
//! writer can size a frame's side information before the SNR search), and the
//! §7.10.1 CRC words.

/// Where the syncframe writer sends its bits.
pub(super) trait Sink {
    /// Append the low `n` (≤ 32) bits of `v`, most significant first.
    fn put(&mut self, v: u32, n: u32);
    /// Bits written so far.
    fn pos(&self) -> usize;
    /// Whether mantissas and skip/aux fill are to be written (false when only
    /// counting side information).
    fn full(&self) -> bool;

    fn bit(&mut self, b: bool) {
        self.put(u32::from(b), 1);
    }
}

/// Counts bits; writes nothing.
#[derive(Default)]
pub(super) struct Counter {
    pub bits: usize,
}

impl Sink for Counter {
    fn put(&mut self, _v: u32, n: u32) {
        self.bits += n as usize;
    }
    fn pos(&self) -> usize {
        self.bits
    }
    fn full(&self) -> bool {
        false
    }
}

/// Writes into a fixed-size, zero-initialised frame buffer.
pub(super) struct Writer {
    pub buf: Vec<u8>,
    pos: usize,
}

impl Writer {
    pub fn new(bytes: usize) -> Self {
        Self {
            buf: vec![0; bytes],
            pos: 0,
        }
    }
}

impl Sink for Writer {
    fn put(&mut self, v: u32, n: u32) {
        debug_assert!(n <= 32);
        debug_assert!(n == 32 || v >> n == 0, "value {v} does not fit in {n} bits");
        for i in (0..n).rev() {
            if (v >> i) & 1 != 0 {
                self.buf[self.pos / 8] |= 0x80 >> (self.pos % 8);
            }
            self.pos += 1;
        }
    }
    fn pos(&self) -> usize {
        self.pos
    }
    fn full(&self) -> bool {
        true
    }
}

/// CRC-16 register, generator x¹⁶ + x¹⁵ + x² + 1 (0x8005), zero initial
/// state, MSB first — the LFSR of §7.10.1. For a byte string `m` this is
/// `m(x)·x¹⁶ mod g(x)`.
pub(super) fn crc16(data: &[u8]) -> u16 {
    let mut crc: u16 = 0;
    for &b in data {
        crc ^= u16::from(b) << 8;
        for _ in 0..8 {
            crc = if crc & 0x8000 != 0 {
                (crc << 1) ^ 0x8005
            } else {
                crc << 1
            };
        }
    }
    crc
}

/// The `crc1` word `w` that makes the register read zero after `w ‖ body`
/// has been shifted in (§7.10.1: "crc1 is generated by encoders such that
/// the CRC calculation will produce zero at the 5/8 point"). The register
/// after `w ‖ body` is `(w·x^L + b)·x¹⁶ mod g` with L the body's bit length,
/// so `w = b·x^(−L) mod g = crc16(body)·x^(−16−L) mod g`. `x` is invertible
/// mod g because g(0) = 1: multiplying by x⁻¹ is adding g when the constant
/// term is set and shifting right.
pub(super) fn crc1_word(body: &[u8]) -> u16 {
    let mut p = u32::from(crc16(body));
    for _ in 0..16 + 8 * body.len() {
        if p & 1 != 0 {
            p ^= 0x1_8005;
        }
        p >>= 1;
    }
    p as u16
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn writer_packs_msb_first() {
        let mut w = Writer::new(3);
        w.put(0b101, 3);
        w.put(0b1001101, 7);
        w.put(0x3f, 6);
        w.put(0xa5, 8);
        assert_eq!(w.pos(), 24);
        assert_eq!(w.buf, vec![0b1011_0011, 0b0111_1111, 0xa5]);
    }

    #[test]
    fn crc1_word_zeroes_the_register_and_crc2_closes_the_frame() {
        let body: Vec<u8> = (0..300u32).map(|i| (i * 37 + 11) as u8).collect();
        let w = crc1_word(&body);
        let mut m = w.to_be_bytes().to_vec();
        m.extend_from_slice(&body);
        assert_eq!(crc16(&m), 0);
        // crc2 appended to the whole thing leaves the register at zero too.
        let c2 = crc16(&m);
        m.extend_from_slice(&c2.to_be_bytes());
        assert_eq!(crc16(&m), 0);
        // and agrees with the decoder's check (which skips the syncword)
        let mut frame = vec![0x0b, 0x77];
        frame.extend_from_slice(&m);
        assert!(crate::frame_crc_ok(&frame));
    }
}
